"""Core domain models for Aurel2-Crypto."""

from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any


class AssetCategory(str, Enum):
    """Broad asset categories."""
    CRYPTO = "crypto"
    STABLECOIN = "stablecoin"
    CASH = "cash"


class CryptoAsset(str, Enum):
    """Tradeable crypto assets."""
    BTC = "btc"
    ETH = "eth"
    SOL = "sol"
    AVAX = "avax"
    LINK = "link"
    USDT = "usdt"


class SignalAction(str, Enum):
    """Trading signal actions."""
    HOLD = "hold"
    BUY = "buy"
    SELL = "sell"
    SHORT = "short"
    COVER = "cover"


class PositionSide(str, Enum):
    """Position side for futures/perps."""
    LONG = "long"
    SHORT = "short"


@dataclass(frozen=True)
class Asset:
    """A tradeable crypto asset."""
    symbol: str            # Trading pair on Binance (e.g., "BTC/USDT")
    name: str
    asset_id: CryptoAsset
    category: AssetCategory = AssetCategory.CRYPTO
    perp_symbol: str | None = None  # Perpetual futures symbol (e.g., "BTC/USDT:USDT")


@dataclass
class MomentumScore:
    """Momentum score for an asset at a point in time."""
    asset: Asset
    date: date
    momentum: float       # Return over lookback period
    price: float
    price_lookback: float
    lookback_days: int = 28

    @property
    def is_positive(self) -> bool:
        return self.momentum > 0


@dataclass
class StrategySignal:
    """A trading signal generated by a strategy."""
    strategy_name: str
    date: date
    action: SignalAction
    asset_id: CryptoAsset | None
    confidence: float
    reasoning: str
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "strategy_name": self.strategy_name,
            "date": self.date.isoformat(),
            "action": self.action.value,
            "asset_id": self.asset_id.value if self.asset_id else None,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "metadata": self.metadata,
        }


@dataclass
class Position:
    """A portfolio position (spot or perp)."""
    asset: Asset
    shares: Decimal
    entry_price: float
    entry_date: date
    side: PositionSide = PositionSide.LONG
    current_price: float | None = None
    leverage: float = 1.0

    @property
    def market_value(self) -> Decimal:
        price = self.current_price or self.entry_price
        return abs(self.shares) * Decimal(str(price))

    @property
    def unrealized_pnl(self) -> float:
        if self.current_price is None:
            return 0.0
        diff = self.current_price - self.entry_price
        if self.side == PositionSide.SHORT:
            diff = -diff
        return float(abs(self.shares)) * diff * self.leverage

    @property
    def unrealized_pnl_pct(self) -> float:
        if self.entry_price == 0:
            return 0.0
        pnl_per_unit = self.current_price or self.entry_price
        diff = pnl_per_unit / self.entry_price - 1
        if self.side == PositionSide.SHORT:
            diff = -diff
        return diff * self.leverage


@dataclass
class Trade:
    """A completed trade."""
    date: date
    asset: Asset
    action: SignalAction
    shares: Decimal
    price: float
    commission: float = 0.0
    side: PositionSide = PositionSide.LONG

    @property
    def value(self) -> float:
        return float(abs(self.shares)) * self.price

    @property
    def total_cost(self) -> float:
        return self.value + self.commission


@dataclass
class FundingPayment:
    """A funding rate payment (carry strategy)."""
    timestamp: datetime
    symbol: str
    rate: float
    payment: float  # Positive = received, negative = paid
    position_size: float


@dataclass
class PortfolioSnapshot:
    """Portfolio state at a point in time."""
    date: date
    cash: Decimal
    positions: list[Position]
    total_value: Decimal

    @property
    def position_value(self) -> Decimal:
        return sum((p.market_value for p in self.positions), Decimal("0"))
